<a href="https://colab.research.google.com/github/adelardw/SVD-and-QR/blob/main/SVD_%26_HH_alg_%26_QR_Dec_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# householder algorithm - transform matrix to upper triangular matrix
import numpy as np

p = 8

b = np.random.uniform(-10,848,(p,p))

def householder_method(A:list):
  n = len(A)
  A = np.array(A)
  #zero_iteration
  ort = np.zeros(n)
  ort[0] = 1

  x = list(A.T[0])
  s = (np.dot(x,x)**0.5)
  u = x - s*ort
  f = np.array([u])
  P = np.eye(n) - 2*(f*f.T)/np.dot(u,u)
  R = np.dot(P,A)

  for k in range(1,n - 1):
    ort = np.zeros(n)
    x = list(R.T[k])
    x = np.array(x)
    x[:k] = 0
    ort[k] = 1
    s = (np.dot(x,x)**0.5)
    u = x - s*ort
    f = np.array([u])
    P = np.eye(n) - 2*(f*f.T)/np.dot(u,u)
    R = np.dot(P,R)
  return np.around(R)


householder_method(b)


array([[1592.,  430.,  930., 1162.,  909.,  648., 1187.,  834.],
       [  -0.,  515.,   49.,  496.,  283.,   79.,  446.,  402.],
       [  -0.,    0.,  671.,  408.,  103.,   15.,  434.,  177.],
       [   0.,   -0.,   -0.,  541., -145.,   86.,   30.,   20.],
       [  -0.,    0.,    0.,    0.,  452.,  236.,   68.,  186.],
       [   0.,   -0.,    0.,   -0.,    0.,  668.,  524.,   -9.],
       [   0.,   -0.,    0.,    0.,   -0.,   -0.,  469.,  205.],
       [   0.,   -0.,   -0.,   -0.,    0.,   -0.,   -0.,  245.]])

In [20]:
# QR-decomposition : A = QR: QQ.T = E , R - upper triangular matrix
import numpy as np

a = np.random.randint(0,2,(8,8))
print(a,'\n')
print("\n Numpy Q \n",np.around(np.linalg.qr(a)[0],3),"\n\n Numpy R \n",np.around(np.linalg.qr(a)[1],3))

def QR_decompositon_h(A:list):
  n = len(A)
  A = np.array(A)
  # zero_iteration
  Q = np.eye(n)
  ort = np.zeros(n)
  ort[0] = 1

  x = list(A.T[0])
  s = (np.dot(x,x)**0.5)
  u = x - s*ort
  f = np.array([u])
  P = np.eye(n) - 2*(f*f.T)/np.dot(u,u)
  Q = np.dot(Q,P)
  R = np.dot(P,A)

  for k in range(1,n-1):
    ort = np.zeros(n)
    x = list(R.T[k])
    x = np.array(x)
    x[:k] = 0
    ort[k] = 1
    s = (np.dot(x,x)**0.5)
    u = x - s*ort
    f = np.array([u])
    P = np.eye(n) - 2*(f*f.T)/np.dot(u,u)
    Q = np.dot(Q,P) 
    R = np.dot(P,R)
  return Q, R


print("Numerical Q \n",np.around(QR_decompositon_h(a)[0],3),"\n")
print("Numerical R \n",np.around(QR_decompositon_h(a)[1],3))

#print("\n Numpy Q \n",np.around(np.linalg.qr(a)[0],3),"\n\n Numpy R \n",np.around(np.linalg.qr(a)[1],3))


[[0 1 1 1 1 1 1 0]
 [0 1 1 1 0 0 0 1]
 [1 1 0 0 1 0 1 1]
 [1 0 0 0 0 1 0 1]
 [1 1 1 1 0 0 0 1]
 [1 0 1 1 1 1 1 1]
 [1 0 0 1 1 1 1 0]
 [0 1 1 0 1 1 0 0]] 


 Numpy Q 
 [[ 0.    -0.488  0.179  0.336  0.321  0.323  0.533  0.354]
 [-0.    -0.488  0.179  0.336 -0.335  0.025 -0.063 -0.707]
 [-0.447 -0.293 -0.646 -0.144  0.238 -0.365  0.235 -0.177]
 [-0.447  0.195 -0.072 -0.312 -0.251  0.714  0.235 -0.177]
 [-0.447 -0.293  0.108  0.024 -0.587 -0.187 -0.204  0.53 ]
 [-0.447  0.195  0.682 -0.144  0.238 -0.365  0.235 -0.177]
 [-0.447  0.195 -0.072  0.576  0.363  0.204 -0.502 -0.   ]
 [-0.    -0.488  0.179 -0.552  0.363  0.204 -0.502  0.   ]] 

 Numpy R 
 [[-2.236 -0.894 -0.894 -1.342 -1.342 -1.342 -1.342 -1.789]
 [ 0.    -2.049 -1.561 -0.878 -0.878 -0.39  -0.39  -0.683]
 [ 0.     0.     1.327  1.076  0.323  0.897  0.143  0.251]
 [ 0.     0.     0.     1.127  0.072 -0.096  0.623 -0.24 ]
 [ 0.     0.     0.     0.     1.523  1.034  1.16  -0.699]
 [ 0.     0.     0.     0.     0.     1.079 -0.204 -

In [21]:
# We should using hessenberg's matrixs or triadiagonal matrixes for QR- algortihm
import numpy as np
import scipy.linalg as sp


g = 10
np.random.seed(5)
matr = np.random.randint(0,2,(g,g))

def hessenberg_matrix(A:list):
  n = len(A)
  A = np.array(A)
  u = np.zeros(n)
  for k in range(n-1):
    alpha = - np.sign(A[k + 1][k])*np.sqrt((np.array([(A[j][k])**2 for j in range(k + 1,n)])).sum())
    r = np.sqrt(0.5*(alpha**2 - A[k + 1][k]*alpha))
    u[:k+1] = 0
    u[k + 1] = (A[k + 1][k] - alpha)/(2*r)
    for j in range(k + 2, n):
      u[j] = A[j][k]/(2*r)  
    v = np.array([u])
    P = np.eye(n) - 2*v*v.T
    A = np.dot(np.dot(P,A),P.T)
  return np.around(A,8)

print('Numerical \n',hessenberg_matrix(matr),"\n\n")
print('Scipy \n',sp.hessenberg(matr),"\n\n")
print('Symmetrical matrixes have transforms to tridiagonal \n',hessenberg_matrix(np.dot(matr,matr.T)),"\n\n")

Numerical 
 [[ 1.         -0.57735027  0.65158377 -1.13938826 -0.62338771  0.09667195
   0.24729244  0.13612578  0.31171871 -0.60752746]
 [-1.73205081  2.33333333 -2.12035526  0.06957776 -0.14656923  0.39574085
   0.53610558 -0.2493495   0.35196479 -0.26441972]
 [ 0.         -3.24893145  2.77192982  0.35173473 -0.03002383 -0.90439084
  -0.12742524  0.81181017  0.39132701 -0.13404608]
 [ 0.         -0.         -1.70740606  0.18150993  0.7982813   0.07253171
   0.15503943  0.46967106  0.1785959   0.23820885]
 [ 0.         -0.         -0.          0.98197934 -0.2271184  -0.1578842
   1.01687435 -0.45799311 -1.1596867   0.06162409]
 [ 0.         -0.          0.         -0.         -0.67018798  0.12405987
   0.43998667 -0.13139643 -0.85846142 -0.14459788]
 [ 0.         -0.         -0.         -0.          0.          1.47455029
  -0.05691954 -0.65025074 -0.03538017 -0.14962379]
 [ 0.          0.          0.          0.          0.         -0.
  -1.2962432   0.17877433  0.06427454 -0.2795141

In [22]:
# QR - algorithm: you sholud using only Hessebergs matrix or tridiagonal matrix's
import numpy as np
import scipy.linalg as sp

def QR_alg(A:list):
  len_a = len(A)
  iteration = 5000
  q0 = np.eye(len_a)
  for i in range(iteration):
    q,r = QR_decompositon_h(A)
    A = np.dot(r,q)
    q0 =np.dot(q0, q)
  #print(A)
  eigen_values = sorted([A[i][i] for i in range(len_a)])
  eigen_vect_matrix = np.array(q0.T)
  return np.array(eigen_values), eigen_vect_matrix

np.random.seed(2)
lambda_l = 5
test_one = np.random.uniform(0,2,(lambda_l ,lambda_l))
eig_val, eig_vect = QR_alg( (test_one + np.conjugate(test_one).T)/2)
ev, ec = np.linalg.eig((test_one + np.conjugate(test_one).T)/2)
print('Numerical eigen values \n',eig_val,'\n')
print('Numpy eigen values\n',ev,'\n')

Numerical eigen values 
 [-1.11677173 -0.54367852  0.15389132  0.78527436  4.21917444] 

Numpy eigen values
 [ 4.21917444  0.78527436 -1.11677173  0.15389132 -0.54367852] 



In [24]:
# SVD

np.random.seed(9)
m = 100
n = 20
a = np.random.randint(0,2,(m,n))

def sv_d(A:list):
  # m >= n
  U = QR_alg(np.dot(A,A.T))[1].T
  m = len(U)
  V = QR_alg(np.dot(A.T,A))[1]
  n = len(V)
  v = (QR_alg(hessenberg_matrix(np.dot(A.T,A)))[0]**0.5)
  singular = np.zeros((m,n))
  for i in range(n):
    singular[i][i] = v[n - i -1]
  return U,singular,V

np.around(sv_d(a)[1],4)

array([[23.1142,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  6.6725,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  6.5447, ...,  0.    ,  0.    ,  0.    ],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [25]:
np.around(sv_d(a)[0],4)

array([[ 0.0892,  0.084 , -0.1151, ..., -0.0991, -0.0292,  0.0027],
       [ 0.039 ,  0.1265,  0.1213, ..., -0.0261, -0.1189,  0.0343],
       [ 0.127 ,  0.055 , -0.093 , ...,  0.1749, -0.0453,  0.0963],
       ...,
       [ 0.0635,  0.0581, -0.189 , ..., -0.1556,  0.0981,  0.1607],
       [ 0.1073,  0.2508,  0.1015, ...,  0.009 , -0.0555,  0.0539],
       [ 0.0996, -0.1907, -0.0818, ...,  0.0569, -0.3045, -0.2045]])